Repository My-Pack/MyPack-iOS, pull requests merged in 2023-03, with the labels that each got.

#11 [#7] 라벨링 파일 삭제
  .gitignore
  labels.json
  package-lock.json
  package.json
Labels: 🫠 Low

#12 [#8] pre-commit 적용
  .githooks/pre-commit
Labels: ✍️ Review

#13 [#8] workflows ci 적용
  .github/workflows/swift.yml
Labels: ✍️ Review

#14 [#8] ci workflow 수정
  .github/workflows/swift.yml
  MyPack.xcodeproj/project.pbxproj
  MyPack.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyPack.xcodeproj/xcshareddata/xcschemes/MyPack.xcscheme
  README.md
Labels: 🫠 Low

#15 [#8] cd workflow 추가
  .github/workflows/swift.yml
  .github/workflows/testflight_upload.yml
Labels: 🫠 Low

#16 [#8] ci workflow 수정
  .github/workflows/swift.yml
Labels: 🚨 HotFix

#17 [#8] fastlane 수정
  fastlane/Fastfile
Labels: 🚨 HotFix

#18 [#8] 슬랙 웹훅 링크 수정
  fastlane/Fastfile
Labels: 🚨 HotFix

#20 [#8] cd workflow 수정
  .github/workflows/testflight_upload.yml
  MyPack.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Matchfile
Labels: 🫠 Low

#21 [#7] pr 템플릿 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🫠 Low

#23 [#7] pr 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🫠 Low

#19 [#9] ui test code 예시 작성
  MyPackUITests/MyPackUITests.swift
Labels: ✍️ Review

#27 [#26] main view ui
  .circleci/config.yml
  .pre-commit-config.yaml
  MyPack.xcodeproj/project.pbxproj
  MyPack/AppDelegate.swift
  MyPack/SceneDelegate.swift
  MyPack/ViewController.swift
  MyPack/model/MainModel.swift
  MyPack/view/MainTabBarView.swift
  MyPack/view/TabView/FirstViewController.swift
  MyPack/view/TabView/SecondViewContorller.swift
  MyPack/view/TabView/ThirdViewController.swift
  MyPack/viewModel/MainTabBarVM.swift
  MyPack/viewModel/TabViewModel/FirstViewModel.swift
  MyPack/viewModel/TabViewModel/SecondViewModel.swift
  MyPack/viewModel/TabViewModel/ThirdViewModel.swift
Labels: 🛠 Working
